### ISSUE TITLE
Port Forwarding

### ISSUE THREAD

**Issue by DarkUlixes** [LiveOverflow/PwnAdventure3#1]
I'm running the server in my home network. Which ports do I need to forward for it to be accessed from the internet?

**Comment by KuroAku** [comment]
With the setup in the docker-compose as is, the ports are forwarded to the host. If you want to forwards  the ports to the Internet from the host check your config in your host and in your router

**Comment by fritz-net** [comment]
this is taken form the readme:
`docker ps -a`
`84343f81034f pwn3server "/opt/pwn3/setup/gam…" 0.0.0.0:3000-3010->3000-3010/tcp, 5432/tcp pwnadventure3_game_1`



maybe port 3000 to 3010 and 5432 are the ports you are looking for?

also try this nice command `netstat -tulpen` it will tell you a lot about your open ports

**Comment by bennieboj** [comment]
You need to open ports 3000 to 3010 since these are the game servers.
Also people need to be able to connect to the master server, that is on port 3333.

You should NOT open port 5432, which is the database port.
