### ISSUE TITLE
Failed to load master server certificate

### ISSUE THREAD

**Issue by ProfessorChill** [LiveOverflow/PwnAdventure3#18]
I've just followed the docker installation, the server is running fine, it connects to the game server and master server.
Now when I try to launch the game and join the server I just get the error `Failed to load master server certificate` however there is a certificate in both the master server and the client.
I'm a bit lost, thanks for any help!

**Comment by ProfessorChill** [comment]
I edited nothing, played offline for a bit, re-launched the server (for the 10th time) and for no reason it worked.... Whelp, time to learn!

**Comment by amar-laksh** [comment]
> I edited nothing, played offline for a bit, re-launched the server (for the 10th time) and for no reason it worked.... Whelp, time to learn!

Hey, I am suffering the same problem and it doesn't seem to work. I've killed the containers multiple times and it still is showing the same "Failed to load master server certificate".

**Comment by amar-laksh** [comment]
So, finally figured out this. Writing it down to prevent future hair loss of other people. 

You don't wanna run the binary from any directory. It will not throw any errors if you cd to the directory and then run the binary.
Basically DO THIS: 
`cd ./client/PwnAdventure3_Data/PwnAdventure3/PwnAdventure3/Binaries/Linux/ && \
        ./PwnAdventure3-Linux-Shipping`
and NOT THIS:
`./client/PwnAdventure3_Data/PwnAdventure3/PwnAdventure3/Binaries/Linux/PwnAdventure3-Linux-Shipping`
