### ISSUE TITLE
error while loading shared libraries: libssl.so.1.0.0 and libcrypto.so.1.0.0

### ISSUE THREAD

**Issue by shahriar0247** [LiveOverflow/PwnAdventure3#22]
![Screenshot from 2020-01-07 16-09-04](https://user-images.githubusercontent.com/47810596/71887373-2415f500-3168-11ea-9894-a88f1e2e0a6a.png)
Steps to reproduce:

1. Download client ( main game file ) [http://www.pwnadventure.com/PwnAdventure3_Linux.zip](url)
2. Download launcher ( hidden inside webpage ) [http://www.pwnadventure.com/PwnAdventure3_Launcher_Linux.zip
3. Extract both into seperate folders and copy PwnAdventure3 from client to PwnAdventure3_data folder
![Screenshot from 2020-01-07 16-15-11](https://user-images.githubusercontent.com/47810596/71887742-e8c7f600-3168-11ea-9a34-c77b9bdf7d1f.png)
4. Starting with the launcher keeps waiting in 'Checking for update' ( forever)
![Screenshot from 2020-01-07 16-16-29](https://user-images.githubusercontent.com/47810596/71887828-1614a400-3169-11ea-8078-b5d98d8627a4.png)
5. Starting the game manually from inside the folder gives this error.

Notes: 
I researched about this and found out "libssl.so.1.0.0" has security issues thats why it has been removed. 

My system:
Linux pop-os 5.3.0-20-generic #21+system76~1572304854~19.10~8caa3e6-Ubuntu SMP Tue Oct 29 00:4 x86_64 x86_64 x86_64 GNU/Linux

**Comment by shahriar0247** [comment]
I fixed this myself. I located the required files and copied them from the steam folder to usr/lib

first download 
the "i386-linux-gnu" files and put them in /lib/i386-linux-gnu/ 

then download
the "x86_64-linux-gnu" files and put them in /lib/x86_64-linux-gnu/

Here is the link to download
https://mega.nz/#F!0BJCjQKa!jFeIaGptmpFtrWgFl8VL1Q

and it should be like this
![Screenshot from 2020-01-07 16-51-15](https://user-images.githubusercontent.com/47810596/71890196-f59b1880-316d-11ea-84a8-3cae3036fee3.png)

**Comment by andersonbosa** [comment]
@shahriar0247  It is not a security good practice to use user links. Can't you offer the place where you downloaded it? Or did you create the lib?

**Comment by shahriar0247** [comment]
Actually I copied the libs from my linux. By finding them, then I uploaded it to mega

**Comment by gitmpr** [comment]
you can add an older apt repository to your sources list and install libssl1.0.0 alongside v1.1 without replacing it.
https://itectec.com/ubuntu/ubuntu-ubuntu-20-04-libssl-so-1-0-0-cannot-open-shared-object-file-no-such-file-or-directory/

**Comment by shahriar0247** [comment]
Thank you for that

**Comment by ThePraeceps** [comment]
Above solution will no longer work due apt-secure. This is of course by-passable but a better solution is:

- Download .deb from Ubuntu source: http://security.ubuntu.com/ubuntu/pool/main/o/openssl1.0/ (make sure it's the regular package not the development one)
- Extract the package with `dpkg-deb -xv libssl1.0.0_1.0.2n-1ubuntu5.10_amd64.deb`
- Move the extracted `./usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0` and `./usr/lib/x86_64-linux-gnu/libssl.so.1.0.0` to the game binary directory (`./PwnAdventure3/PwnAdventure3/Binaries/Linux/`)
