### ISSUE TITLE
Error. Docker compose up.

### ISSUE THREAD

**Issue by MNOGOZNAAL** [LiveOverflow/PwnAdventure3#32]
![Screenshot_3](https://user-images.githubusercontent.com/38400600/120896661-5a4cf200-c644-11eb-95d8-d5b38b8b50d2.png)

**Creating pwnadventure3_master_1 ... error**
I did everything right, all files are uploaded. Please help me.

**Comment by MNOGOZNAAL** [comment]
I fixed it.

**Comment by ma1ware07** [comment]
Encountered the same error message today, do you remember how exactly you fixed this issue?

**Comment by MNOGOZNAAL** [comment]
you can just create the postgres-data directory in /home/user/PwnAdventure3/

вт, 1 февр. 2022 г. в 16:14, ma1ware07 ***@***.***>:
